
/**
 * FreeIMU calibration header. Automatically generated by octave AccMagnCalib.m.
 * Do not edit manually unless you know what you are doing.
*/

// following example of calibration.h
#ifndef CALIBRATION_H
#define CALIBRATION_H

const int acc_off_x = 0;
const int acc_off_y = 0;
const int acc_off_z = 0;
const float acc_scale_x = 1.0f;
const float acc_scale_y = 1.0f;
const float acc_scale_z = 1.0f;

const int magn_off_x = 0;
const int magn_off_y = 0;
const int magn_off_z = 0;
const float magn_scale_x = 1.0f;
const float magn_scale_y = 1.0f;
const float magn_scale_z = 1.0f;

#endif
